/*
 * Waiting List Api
 *
 * Ambulance Waiting List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xcernak@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wac_project

type AppointmentsList struct {

	// Unique id of the appointment in this appointments list
	Id string `json:"id"`

	// Name of patient in appointments list
	Name string `json:"name,omitempty"`

	// Date of the appointment
	Date string `json:"date"`

	// Estimated start time of the appointment
	EstimatedStart string `json:"estimatedStart"`

	// Estimated end time of the appointment
	EstimatedEnd string `json:"estimatedEnd"`

	// Indicate whether appointment is allocated to patient or not
	PatientAppointed bool `json:"patientAppointed"`

	// Describes reason of the appointment
	Condition string `json:"condition,omitempty"`

	// Additional information related to the appointment written by doctor
	DoctorNote string `json:"doctorNote,omitempty"`
}
